on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: test-await-maven-artifact
        uses: ./.github/actions/await-maven-artifact
        with:
          groupid: 'co.elastic.apm'
          artifactid: 'apm-agent-java'
          version: '1.42.0'